# Site settings
title: Numan Aytemiz's Study Notes
email: ahmetnumanaytemiz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My Study and learning journey in the cyber security.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://numanaytemiz.github.io" # the base hostname & protocol for your site
twitter_username: ahmetnumanaytem
github_username: numanaytemiz

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Cyber Security Specialist"
excerpt_separator: "<!--more-->"
# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
